/* ============================================================
   전국 지리 마스터 퀴즈 - 지역 특징/역사 콘텐츠 데이터
   ------------------------------------------------------------
   구조: 구 이름 => {
     desc:    지리·기본 설명 (필수)
     history: 역사적 의미/사건 (선택)
     people:  관련 인물 (선택)
     images:  [{ src: "사진주소", caption: "설명" }, ...] (선택)
   }
============================================================ */
const GU_FEATURE_EN = {
  // ── 서울 25개 구 ──

  "강남구": {
    desc: "An autonomous district located east of the Han River in Seoul, it is a major commercial and business hub centered around Teheran-ro. It is home to COEX and Bongeunsa Temple, and is also well known as an area with a strong emphasis on education.",
    history: "Situated on the northwestern slopes of Mount Guryong and Mount Daemo, as well as on the hills and plains north and south of Yangjae Stream, the area has been inhabited since the Paleolithic Era, and Bronze Age settlement sites have been confirmed in Yeoksam-dong. During the Three Kingdoms period, it was a battleground for the struggle over the Han River basin, and traces of the Samseong-dong earthen fortress and Daemo Mountain Fortress remain. During the Joseon Dynasty, it was a rural area along the Han River belonging to Eonju-myeon and Daewang-myeon of Gwangju-bu; the freshwater crabs from Apgujeong were famous as tribute items to the royal court. It was incorporated into Seoul in 1963, and in 1975, Gangnam District was newly established from Seongdong District; subsequently, Gangdong District and Seocho District were successively separated from it. Following the 1970 South Seoul Development Plan and the opening of the Hannam Bridge and the Gyeongbu Expressway, the area experienced rapid growth and has become one of Seoul’s leading urban centers today; as a result, the term 'Yeongdong,' derived from its old name, is still used in some contexts.",
    people: "Bongeunsa Temple in Samseong-dong is said to have been founded during the Silla period and played an important role as the royal temple of the Joseon dynasty. Its front courtyard is called ‘Seunggwa-pyeong’ (Monk Examination Ground) because, during the reign of King Myeongjong, Monk Bowo presided over the monk examination there with the support of Queen Munjeong, attracting thousands of monks from across the country. There is also the ‘Bo-eun-dan Folklore,’ which tells of Hong Sun-eon, an interpreter from Cheongdam-dong, who helped a woman in distress in China; that woman later became the wife of a high-ranking Ming official and provided significant assistance during the Imjin War. In addition, there are tales such as the story of the Stele of King Taejong at Heonreung, which is said to sweat when the nation faces calamity, and the legend of Maljuk-geori, which originated from King Injo’s escape.",
    images: [
      { src: "Image/gangnam-1.jpg", caption: "Stories of Bongeunsa Temple, Seunggwa-pyeong, and Boeun-dan (AI-generated image)" }
    ]
  },

  "강동구": {
    desc: "Located at the southeastern tip of Seoul, south of the Han River, this autonomous district is an area steeped in history, home to the Amsa-dong Prehistoric Site. It consists primarily of residential areas and boasts a pleasant natural environment, including Ilja Mountain and the banks of the Han River.",
    history: "Gangdong-gu marks the beginning of Seoul’s history. Amsa-dong is home to one of Korea’s most representative archaeological sites of a Neolithic-era settlement, where people lived approximately 6,000 years ago. The site gained recognition in 1925 when the Great Flood of the Year of the Ox eroded the riverbank, exposing comb-patterned pottery. Due to its proximity to Pungnap Fortress—believed to be the capital of the Baekje Kingdom across the Han River—it served as a center of Baekje culture and was also the ancestral home of the Gwangju Lee clan and the scholar Dunchon Lee Jip during the late Goryeo Dynasty. During the Joseon Dynasty, it was a rural area belonging to Gucheon-myeon, Gwangju-bu, and served as a timber collection point where rafts from Gangwon Province would stop before traveling down to Mapo. After being incorporated into Seoul in 1963, it was separated from Gangnam-gu in 1979 to become Gangdong-gu. Subsequently, Songpa-gu was established as a separate district in 1988.",
    people: "Duncheon-dong derives its name from the pen name of Lee Jip (李集), a scholar from the late Goryeo period. Lee Jip was renowned for his profound filial piety; a legend known as the ‘Gukcheongsa Well’ tells how he cured his father’s boil using a golden carp from the well water he obtained after offering a hundred-day prayer at Gukcheongsa Temple. This well, associated with his filial devotion, is said to still remain within Namhansanseong Fortress today. In Amsa-dong, traces remain of Neolithic people who lived along the riverbank, catching fish and making comb-patterned pottery, demonstrating that Seoul has been inhabited since prehistoric times. In addition, the 'Sangyeo Seonso' songs sung during funeral processions and the 'Bama Taryeong' songs from the 'Dalgujil Nori' folk game have been passed down through the generations.",
    images: [
      { src: "Image/Gangdong-1.jpg", caption: "Duncheon Lee Family’s Seodang, Gukcheongsa Well, and Amsa-dong Comb-Pattern Pottery (AI-generated image)" }
    ]
  },

  "강북구": {
    desc: "Located at the northeastern tip of Seoul, this autonomous district is set against the backdrop of Mount Bukhan—Seoul’s sacred mountain—and consists mostly of pleasant residential areas. It is well known as a region where nature and modern history blend harmoniously, home to the Ui-dong Valley, renowned temples such as Doseonsa and Hwagye Temple, and the National April 19 Democratic Cemetery.",
    history: "During the Three Kingdoms period, it was a strategic stronghold over which Baekje, Goguryeo, and Silla vied for control of Mount Bukhan; King Jinheung designated Mount Bukhan as Silla’s border and erected a commemorative stele. During the Joseon Dynasty, the area belonged to Yangju, outside the capital’s walls. After enduring the Imjin War and the Manchu Invasion, the present-day Bukhansan Fortress was constructed during the reign of King Sukjong to serve as both a refuge and a defensive stronghold. After liberation, the area belonged to Dobong-gu via Seongbuk-gu, but as the population grew significantly, Mia-dong, Beon-dong, Suyu-dong, and Ui-dong were separated from Dobong-gu in 1995 to establish the new Gangbuk-gu. For this reason, it is still often grouped together with Dobong-gu and Nowon-gu as the ‘northeastern region.’",
    people: "Doseonsa Temple in Ui-dong is said to have been founded by National Master Doseon during the late Silla period, while Hwagye Temple still houses a beautiful bronze bell and the Daeungjeon Hall from the late Joseon Dynasty. The National April 19 Democratic Cemetery in Suyu-dong is the final resting place for those who sacrificed their lives during the April 19 Revolution, attracting visitors every year to pay their respects. Additionally, an inscription of 69 characters embodying the spirit of the March 1st Movement remains carved into a rock at the summit of Baegunbong Peak on Mount Bukhansan, making this area a symbolic site of national spirit. The Mia-dong area is also home to the legend of Turtle Rock, said to have originated from a battle between the Turtle Rock and mountain spirits.",
    images: [
      { src: "Image/Gangbuk-1.jpg", caption: "Doseonsa Temple, Hwagye Temple, April 19 Democratic Cemetery, and the March 1st Movement inscription on Baegunbong Peak (AI-generated image)" }
    ]
  },

  "강서구": {
    desc: "Located on the Gimpo Plain along the lower reaches of the Han River at the western edge of Seoul, this autonomous district serves as the gateway to Seoul, home to Gimpo International Airport. The Hwagok-dong and Magok-dong areas have undergone large-scale development and grown into residential and business districts, while historic cultural heritage sites such as Yangcheon Hyanggyo and Heoga Rock remain preserved.",
    history: "The former name of Gangseo-gu was ‘Jechapawi’ (齊次巴衣), meaning ‘the rock where rituals are performed,’ which is said to have originated from Heoga Rock on the banks of the Han River. During the Three Kingdoms period, the area was ruled alternately by Baekje and Goguryeo, and during the Unified Silla period, it became Gimpo County, belonging to the Gimpo and Yangcheon regions for a long time. In 1963, it was incorporated into Seoul from Gimpo County, Gyeonggi Province, and became part of Yeongdeungpo-gu, before being separated and established as Gangseo-gu in 1977. Later, upon the completion of the Mok-dong New Town development, the areas of Mok-dong, Sinjeong-dong, and Sinwol-dong were re-divided in 1988 to establish Yangcheon District.",
    people: "The Heoga Rock in Gayang-dong is a natural rock cave said to be the birthplace of the Heo clan of Yangcheon. It is said that Heo Jun, the renowned physician who authored the Donguibogam, wrote his book here and passed away at this site. At the foot of Gungsan Mountain stands Yangcheon Hyanggyo, the only Confucian school in Seoul, where the Seokjeon Daeje ritual is held in spring and fall to carry on the spirit of the ancient scholars. There is also a legend that General Kim Mal-son drove away the ‘Ghost Rock,’ which had been threatening the village, by shooting an arrow at it, and that he built Yeongbyeokjeong Pavilion nearby.",
    images: [
      { src: "Image/Gangseo-1.jpg", caption: "Heo-ga Rock (Heo Jun·Donguibogam)·Yangcheon Hyanggyo·Kim Mal-son (AI-generated image)" }
    ]
  },

  "관악구": {
    desc: "Located southwest of Seoul, with the majestic Mount Gwanak as its backdrop, this autonomous district is a major residential area centered around Bongcheon-dong and Sillim-dong. Home to Seoul National University, it boasts a thriving university-area commercial district and is also well known for Nakseongdae, the birthplace of General Gang Gam-chan, a renowned military commander of the Goryeo Dynasty.",
    history: "During the Three Kingdoms period, the area was ruled in turn by Baekje, Goguryeo, and Silla, and during the Goryeo Dynasty, it was known as Geumju (衿州). In the Joseon Dynasty, it was a rural area belonging to Siheung County and Gwacheon County. Legend has it that Mount Gwanak—one of the Five Great Mountains of Gyeonggi—was considered the ‘Mountain of Fire,’ and a Haetae statue was erected in front of Gwanghwamun Gate to suppress the fire energy emanating from Gyeongbokgung Palace. In 1963, it was incorporated into Seoul and became part of Yeongdeungpo-gu, but in 1973, it was separated and established as Gwanak-gu. In 1975, Seoul National University relocated here, and the area has since grown into the university town it is today.",
    people: "Nakseongdae was named after a legend that a large star fell from the sky at the time of General Gang Gam-chan’s birth, and the Inheon Festival is held annually to honor his spirit of patriotism. There are also many legends associated with Gang Gam-chan. One story tells that while trying to eliminate a thunderbolt on Mount Gwanak, he accidentally uprooted all the kudzu vines, which is why kudzu vines are rare on this mountain. Another legend, passed down at Yeollyeoam (Rock of the Virtuous Woman) on Mount Gwanak, tells of a woman who, after losing her husband, remained chaste and prayed so fervently that her entire family was turned into fossils.",
    images: [
      { src: "Image/Gwanak-1.jpg", caption: "Nakseongdae (Kang Gam-chan’s Spirit of Patriotism) · Kudzu on Mount Gwanak · Sillim Oak Trees (AI-generated image)" }
    ]
  },

  "광진구": {
    desc: "Located in eastern Seoul, this autonomous district is nestled between the Han River and Mount Achasan. It is a vibrant, youthful area home to Children’s Grand Park, Konkuk University, and Sejong University. It is a place where the natural beauty of Ttukseom Han River Park and the Achasan area blends harmoniously with the riverside scenery leading to Walker Hill.",
    history: "The Achasan area was a battleground during the Three Kingdoms Period, where Goguryeo, Baekje, and Silla fought over the Han River for about 200 years; Achasan Fortress remains as a testament to that era. During the Joseon Dynasty, the Salgoteui Pasture—a national ranch where the royal family’s horses were raised—was located here in Salgoteui Valley, and the area was also used as the king’s hunting ground. The site, which had been occupied by a golf course during the Japanese colonial period, was developed into Children’s Grand Park in 1973, and in 1995, Gwangjin-gu was established after being separated from Seongdong-gu.",
    people: "Legend has it that the name Achasan originates from an incident during the reign of King Myeongjong, when the renowned fortune-teller Hong Gye-gwan was about to be executed for failing to correctly guess the number of mice in a chest, but the king belatedly realized his mistake, exclaiming, ‘Ah, I was wrong!’ It is said that Yeonghwa Temple on Achasan Mountain was founded by Venerable Uisang during the reign of King Munmu of Silla, and at Gwangnaru, the tradition of the Dragon King Festival (Yangjinsa), where people prayed for safe voyages, remains and continues to this day.",
    images: [
      { src: "Image/Gwangjin-1.jpg", caption: "The Legend of the Mice in the Chest at Honggye-gwan on Achasan Mountain, Yeonghwa Temple (Venerable Uisang), and the Dragon King Festival at Gwangnaru (AI-generated image)" }
    ]
  },

  "구로구": {
    desc: "Located at the southwestern gateway to Seoul, this autonomous district is home to the Seoul Digital Industrial Complex—a high-tech venture hub that emerged from the former Guro Industrial Complex. It is also known as a multicultural commercial district where diverse cultures blend together on the flat terrain through which the Anyangcheon and Mokgamcheon streams flow.",
    history: "During the Three Kingdoms period, this area was the site of continuous struggles among Goguryeo, Baekje, and Silla over control of the Han River basin. During the Goryeo Dynasty, it served as the stronghold of the Geumju Kang clan, descendants of Gang Gam-chan. During the Joseon Dynasty, it was a rural area belonging to Geumcheon County and the Bupyeong Provincial Office, and in 1963, it was incorporated into Yeongdeungpo-gu, Seoul. In 1980, centered around the Guro Industrial Complex, it was separated from Yeongdeungpo-gu to form the new Guro-gu, and in 1995, the areas of Doksan-dong and Siheung-dong were split off to establish Geumcheon-gu.",
    people: "In Cheonwang-dong, a legend is passed down about Prime Minister Ha Yeon, who served as Chief State Councilor during the reign of King Sejong. It is said that his spirit appeared to the new district magistrate, asking him to stop tomb raiders who had entered his burial site. The courageous magistrate granted his request, saving the prime minister’s spirit and even securing a royal pardon. In addition, the legend of the zelkova tree in Gaebong-dong remains, and since the area was a rural village from ancient times, Dodaengje rituals—praying for the village’s safety and a bountiful harvest—were widely practiced throughout the area every Full Moon of the First Lunar Month.",
    images: [
      { src: "Image/Guro-1.jpg", caption: "The Spirit of Prime Minister Ha Yeon in Cheonwang-dong, the Zelkova Tree in Gaebong-dong, and the Dangdangje Festival on the Full Moon of the First Lunar Month (AI-generated image)" }
    ]
  }, 

  "금천구": {
    desc: "Located at the southwestern tip of Seoul along the Anyang Stream, this autonomous district was once the center of the former Siheung County. The Gasan and Doksan-dong areas were developed into the Seoul Digital Industrial Complex (the successor to the Guro Industrial Complex) and have grown into one of Seoul’s leading industrial hubs, home to a high concentration of cutting-edge IT and venture companies.",
    history: "In ancient times, this area was part of the Mahan and Baekje kingdoms. After a period of rivalry among the Three Kingdoms, it was known as Gogyang County during the Unified Silla period and as Geumju (衿州) during the Goryeo period; the name ‘Geumcheon (衿川)’ also originated from this. In particular, the Geumcheon-gu area has been the stronghold of the Geumju Kang clan—descendants of Gang Gam-chan—ever since his ancestors settled there. During the Joseon Dynasty, it belonged to Siheung County and remained a rural area on the outskirts of Seoul for a long time. In 1963, it was incorporated into Seoul and became part of Yeongdeungpo District. Subsequently, in 1980, it was transferred to Guro District, and in 1995, Geumcheon District was newly established by separating Gasan, Doksan, and Siheung-dong from Guro District. Today, the former Guro Industrial Complex has been transformed into the Seoul Digital Industrial Complex.",
    people: "Hoam Mountain in Siheung-dong is home to Hoam Mountain Fortress, said to have been built during the Unified Silla period, demonstrating that the area was a key military stronghold guarding the lower reaches of the Han River. At the foot of the mountain lies Hoapsa Temple, which is said to have been built by King Taejo Yi Seong-gye to suppress the 'fire energy' (hwagi) of Hanyang; legend has it that the temple was constructed at the tail of the tiger-shaped mountain peak to subdue that energy. In addition, several feng shui legends are passed down in this area regarding the selection of the capital at the beginning of the Joseon Dynasty.",
    images: [
      { src: "Image/Geumcheon-1.jpg", caption: "Hoam Mountain Fortress, Hoapsa Temple (founded by King Taejo), and Feng Shui Capital Selection (AI-generated image)" }
    ]
  },  

  "노원구": {
    desc: "Located at the northeastern tip of Seoul, this is a large residential district where the Jungnang Stream flows against the backdrop of Mount Surak and Mount Bulam. Home to large, planned apartment complexes in the Sanggye and Junggye-dong areas, as well as several universities, the Taereung National Training Center, and Taereung itself, this district harmoniously blends education, sports, and the history of the Joseon royal tombs.",
    history: "In ancient times, this was a border region contested by the Three Kingdoms. Following King Jangsu of Goguryeo’s southward expansion, it became part of Maeseong County and later became Naeso County during the Unified Silla period. During the Joseon Dynasty, it belonged to Nowon-myeon in Yangju; ‘Nowon (蘆原)’ means ‘a field overgrown with reeds,’ a name derived from the area’s ancient topography, and there was a large market called Nowonjeon, located at a key junction on the road to Hamgyeong Province. In 1963, it was incorporated into Seoul; after briefly being part of Seongbuk-gu, it became part of Dobong-gu in 1973. As the population grew explosively, the areas of Sanggye, Junggye, Hagye, and Wolgye-dong were separated from Dobong-gu in 1988 to establish the new Nowon-gu. Subsequently, with the development of the new Sanggye and Junggye residential districts, it has established itself as a leading residential area in northeastern Seoul.",
    people: "Gongneung-dong is home to Tae-neung, the tomb of Queen Munjeong of the Joseon Dynasty, and Gangneung, the tomb of King Myeongjong, which remain important heritage sites showcasing the Joseon royal tomb system. The area around Taereung is widely known as an iconic site for Korean sports, home to the Taereung National Training Center—once the cradle of national athletes—as well as the International Shooting Range and Ice Rink. Additionally, the area is home to the touching legend of a hunter and his son associated with the name of Suraksan Mountain, and the legend of Bulamsan Mountain, which is said to have turned away after failing to become Namsan Mountain.",
    images: [
      { src: "Image/Nowon-1.jpg", caption: "Taereung, Gangneung (Queen Munjeong and King Myeongjong), Taereung Athletes’ Village, and Hagrimsa Temple (AI-generated image)" }
    ]
  },

  "도봉구": {
    desc: "As the northernmost gateway to Seoul, this is a pleasant residential area where the Jungnang Stream flows against the backdrop of the towering Mount Dobong. It is known as a place where nature, history, and culture harmoniously blend, featuring Dobong Seowon and various hermitages at the foot of Mount Dobong, as well as the Tomb of Prince Yeonsan in Banghak-dong and the Kim Soo-young Literature Museum.",
    history: "In ancient times, it was a strategic location successively occupied by Baekje, Goguryeo, and Silla. It was known as Maeseong-gun during the Goguryeo period, Naeso-gun during the Unified Silla period, and Gyeonju (見州) during the Goryeo period, before being incorporated into Yangju. During the Joseon Dynasty, it belonged to Yangju, where place names such as Chang-dong, Dobong, Banghak, and Ssangmun took root. In 1963, it was incorporated into Seoul and became part of Seongbuk-gu. In 1973, Dobong-gu was established as a separate district split from Seongbuk-gu, and subsequently, Nowon-gu was separated in 1988 and Gangbuk-gu in 1995, resulting in the area’s current configuration. For this reason, it is still often grouped together with Gangbuk-gu and Nowon-gu as Seoul’s ‘northeastern region’.",
    people: "Banghak-dong is home to the tombs of King Yeonsan, who caused two political upheavals before being deposed in a counter-revolution, and his wife, Lady Shin of Geochang; next to them stands a ginkgo tree that has lived for a thousand years and has been designated as Seoul’s No. 1 Protected Tree. On Chosan Mountain in Chang-dong, there are approximately 1,000 tombs of people from various social classes, including those of eunuchs from the Joseon Dynasty, which illustrate the evolution of ancient burial customs and stone artifacts. Additionally, in Ssangmun-dong, the story of the 'Ssangmun' (Double Gate)—a gate erected to honor three generations of filial piety—has been passed down, and this became the origin of the neighborhood’s name.",
    images: [
      { src: "Image/Dobong-1.jpg", caption: "Tomb of King Yeonsan, Tomb of the Geochang Shin Clan, Ginkgo Tree, Chosan Mountain Tomb Complex, Ssangmun Filial Piety Gate (AI-generated image)" }
    ]
  },

  "동대문구": {
    desc: "Located in northeastern Seoul, just outside Heunginmun (Dongdaemun), this autonomous district has long served as the eastern gateway to the capital. It is a key transportation hub centered around Cheongnyangni Station and a center for the trade of traditional Korean medicine, home to Seoul Yakryeongsi (Gyeongdong Market). It is also a region steeped in history, where the Seonongdan—a site where kings of the Joseon Dynasty encouraged farming and performed ancestral rites—still stands.",
    history: "During the Three Kingdoms period, it was a border region where Baekje, Goguryeo, and Silla vied for control of the Han River basin. In the Joseon Dynasty, it was part of the ‘Seongjeo Sipri’ (Ten Li Outside the Capital) and was organized into the Sungshin-bang and Inchang-bang districts outside Heunginmun Gate. This area was symbolically central to the nation’s agricultural policy, as it was home to Seonnongdan—where the king performed the Seonnong ritual to pray for a bountiful harvest—and Dongjeokjeon (East Ritual Field), the royal farm. During the Japanese colonial period, the area grew into a transportation and commercial hub in eastern Seoul following the opening of Cheongnyangni Station. After liberation, administrative boundaries were adjusted several times, and in 1988, parts of the area—including Sinseol-dong, Yongdu-dong, and Jegi-dong—were separated to form Jungnang-gu. As a result, the district now consists of 10 neighborhoods: Jeonnong, Dapsimni, Jang-an, Hoe-gi, Cheongnyangni, Hwigeong, and Imun-dong.",
    people: "At Seonnongdan in Jegi-dong, a juniper tree—said to have been planted in the early Joseon Dynasty—remains designated as a Natural Monument. It is also said that the rice soup the king shared with his people after performing the Seonnong ritual is the origin of today’s ‘seolleongtang.’ In Cheongnyangni-dong, Yeonghwiwon—the tomb of Consort Sunheon, Empress Dowager Eom, a concubine of King Gojong—and Sunginwon, the tomb of his young grandson Lee Jin, stand side by side, offering a glimpse into the burial rites of the Joseon royal family. Furthermore, in Dapsimni-dong and Jeonnong-dong, the tradition of village shrines (dongje-dang) where prayers are offered for the community’s well-being continues to this day.",
    images: [
      { src: "Image/Dongdaemun-1.jpg", caption: "Seonongdan, Origin of Seolleongtang, Yeonghwiwon, Sunginwon, King Sejong Memorial Hall (AI-generated image)" }
    ]
  }, 

  "동작구": {
    desc: "Located in southwestern Seoul, across the Han River from Yongsan and Yeouido, this autonomous district has long served as a key transportation hub connecting the Samnam region with the capital via the Nodul Ferry (Noryangjin). It is a land of loyalty and filial piety, home to the Seoul National Cemetery and the Tombs of the Six Loyal Ministers, and is also widely known for the Noryangjin Fish Market and its academic district.",
    history: "During the Three Kingdoms period, the area alternated between the territories of Baekje, Goguryeo, and Silla. The fact that it was named ‘Jin’ (meaning ‘ferry’) during the Unified Silla period indicates that a ferry crossing had already been established in the Noryangjin area. During the Joseon Dynasty, the area was divided between Gwacheon County and Siheung (formerly Geumcheon), and a village developed along the Samnam-daero road, which crossed the Han River at Dongjakjin and led to Namtaeryeong. Although the ferry’s function disappeared with the construction of the Han River Bridge in 1900 and the opening of the Gyeongin Railway, the area transformed into a key hub for modern transportation. After liberation, the area was part of Yeongdeungpo-gu and Gwanak-gu before being separated from Gwanak-gu in 1980 to form the newly established Dongjak-gu.",
    people: "In Noryangjin Bon-dong, there is the Tomb of the Six Loyal Ministers, which enshrines Seong Sam-mun and the other five ministers who died a martyr’s death while attempting to restore King Danjong to the throne; memorial rites are held there every year to honor their loyalty. The National Seoul Cemetery in Dongjak-dong is the final resting place for patriotic martyrs and national heroes who dedicated their lives to the country, making it a place of remembrance visited by people from all over the nation. There is also a poignant legend that a woman, who had been deeply in love with Park Tae-bo—who died opposing the dethronement of Queen Inhyeon—took her own life on the day Nogang Seowon was completed.",
    images: [
      { src: "Image/Dongjak-1.jpg", caption: "Tomb of the Six Loyal Ministers, Seoul National Cemetery, Yongyang Bongjejeong Pavilion (King Jeongjo’s Filial Piety) (AI-generated image)" }
    ]
  }, 

  "마포구": {
    desc: "Located west of Seoul along the lower reaches of the Han River, this autonomous district was once a logistics hub for the Mapo and Seogang ferry crossings, where grain and seafood from the Samnam region converged during the Joseon Dynasty. Today, it has grown into a hub for the cultural and media industries, epitomized by Hongdae and Sangam Digital Media City.",
    history: "During the Three Kingdoms period, it was caught in the power struggle among Baekje, Goguryeo, and Silla over the Han River basin. During the Joseon Dynasty, it belonged to the Yongsan-bang and Seogang-bang districts—located ten ri outside the capital walls—and flourished as a port along the Han River. The Mapo, Seogang, and Yanghwa ferry crossings served as collection points for grain taxes, seafood, and various goods coming from the Three Southern Provinces and the West Sea, forming the core of logistics on the Han River. In 1944, Mapo-gu was established by separating parts of Seodaemun-gu and Yongsan-gu, and after several boundary adjustments, it came to include Seongsan and Sangam-dong. Although the old port culture faded as Ganghwa Bay was blocked off and land transportation developed, the area has reemerged as a media and cultural hub alongside the development of Sangam-dong.",
    people: "Jamdubong Hill along the Han River in Hapjeong-dong is where countless Catholic believers were martyred during the Byeongin Persecution; it is known as ‘Jeoldu-san’ (Mount Beheading) and is now home to a martyrs’ shrine and a memorial hall. In Dohwa-dong, the neighborhood takes its name from the legend of Dohwa Nangja, which is said to have originated from a peach tree planted by a father who longed for his daughter—who had become the daughter-in-law of the Jade Emperor. Additionally, in Tojeong-dong, the site of the birthplace of Tojeong Lee Ji-ham—who is said to have authored Tojeong Bigyeol—remains, demonstrating that Mapo is a region steeped in a long history of scholarship and stories.",
    images: [
      { src: "Image/Mapo-1.jpg", caption: "Jeoldu-san Martyrs’ Shrine, Mangwonjeong Pavilion (Prince Hyoryeong), Birthplace of Tojeong Lee Ji-ham (AI-generated image)" }
    ]
  },

  "서대문구": {
    desc: "Located in northwestern Seoul, just outside Donuimun (Seodaemun)—one of the four major gates of the old capital—this autonomous district blends the green spaces at the foothills of Inwangsan and Ansan mountains with the university district of Sinchon. It is an educational hub with a high concentration of universities, including Yonsei University and Ewha Womans University, and a symbolic site of the anti-Japanese independence movement, home to Independence Gate and the Seodaemun Prison History Museum.",
    history: "During the Three Kingdoms period, it was a border region where Baekje, Goguryeo, and Silla vied for control of the Han River basin. During the Goryeo Dynasty, it was known as Namgyeong, and after the founding of the Joseon Dynasty, it was incorporated into Hanseong-bu, serving as the western gateway to the capital. The area was home to Mohwagwan and Yeongeunmun, where envoys from the Ming and Qing dynasties were received, serving as a gateway for foreign exchanges; during the late Joseon period, it belonged to the Banseok-bang and Bansong-bang districts, as well as the Yeonhui and Yeon-eun-bang areas of Seongjeo-sipri. In 1943, Seodaemun-gu was established following the implementation of the district system; subsequently, Mapo-gu was separated in 1944 and Eunpyeong-gu in 1979, resulting in the district’s current configuration. In modern times, with the establishment of universities and missionary organizations in the Sinchon area, it has grown into a leading educational and cultural hub representing Seoul.",
    people: "In Hyeonjeo-dong, Independence Gate—erected by the Independence Association on the site of Yeongeunmun Gate, where Qing envoys were once received—still stands as a symbol of the will for independence. Next to it, Seodaemun Prison, where numerous independence activists endured imprisonment, has been preserved as a historical museum. Bongwon Temple in Bongwon-dong is said to have been founded by National Preceptor Doseon during the Silla period; it is a place where the Buddhist ritual Yeongsanjae is passed down as a National Intangible Cultural Heritage. Additionally, there is a legend passed down about a filial son who, while traveling back and forth to his father’s grave at Muakjae, was carried on the back of a tiger.",
    images: [
      { src: "Image/Seodaemun-1.jpg", caption: "Independence Gate, Seodaemun Prison History Museum, and Yeongsanjae at Bongwon Temple (AI-generated image)" }
    ]
  }, 

  "서초구": {
    desc: "Located in southern Seoul, this autonomous district faces the Han River with Mount Cheonggye and Mount Umyeon as its backdrop. Along with Gangnam, it is one of Seoul’s leading residential and business hubs. Home to the Seoul Arts Center, the National Library of Korea, the Supreme Court, and the Supreme Prosecutors’ Office, it serves as a center for culture and the judiciary; it is also the site of Heonneung and Inneung, royal tombs from the Joseon Dynasty.",
    history: "During the Three Kingdoms period, the area was caught in the power struggle among Baekje, Goguryeo, and Silla over the Han River basin. During the Unified Silla period, it was part of Yuljin County; during the Joseon Dynasty, it was a rural area south of the capital, belonging to Eonju-myeon in Gwangju County and Gwacheon County. As it lay on the route connecting the capital to the Samnam region, a post station village known as ‘Maljuk-geori’ developed in the area now known as Yangjae-dong. After being incorporated into Seoul in 1963, it became part of Gangnam-gu in 1975. In 1988, 11 statutory neighborhoods—including Seocho, Jamwon, Banpo, Bangbae, and Yangjae-dong—were separated from Gangnam-gu to form the newly established Seocho-gu. Triggered by the Yeongdong Land Readjustment Project that began in 1968, the area underwent rapid urbanization and developed into the planned city it is today.",
    people: "In Naegok-dong, Heon-neung—the tomb of King Taejong and Queen Wongyeong—and In-neung—the tomb of King Sunjo and Queen Sunwon—stand side by side, serving as important heritage sites that illustrate the burial rites of the Joseon royal family. The Seoul Arts Center, located at the foot of Umyeon Mountain, features an opera house modeled after a scholar’s hat and a fan-shaped concert hall, forming a complex cultural and arts space alongside the National Center for Korean Traditional Performing Arts and the Korea National University of Arts. Additionally, in Banpo-dong, a legend is passed down about Beolbawi Rock and Malmudeum—a story in which a swarm of bees emerged to punish a soldier after he killed a baby whose umbilical cord had been cut with a reed.",
    images: [
      { src: "Image/Seocho-1.jpg", caption: "Heonneung, Inneung, Seoul Arts Center, Yangjae Citizens’ Forest, and the Yoon Bong-gil Memorial Hall (AI-generated image)" }
    ]
  },

  "성동구": {
    desc: "This autonomous district is located in the Wangsimni area, east of downtown Seoul, where the Cheonggyecheon and Jungnangcheon streams converge and flow into the Han River. Once home to Salgoteui Valley—a royal hunting ground during the Joseon Dynasty—and horse pastures, it is now emerging as a new cultural hotspot in Seoul, best known for the handmade shoe district and café district in Seongsu-dong.",
    history: "The discovery of comb-patterned pottery and Bronze Age artifacts at the foot of Eungbong Mountain in Oksoo-dong along the Han River demonstrates that people have lived here since the Neolithic Age. During the Three Kingdoms Period, it served as a strategic stronghold over which the three kingdoms vied for control of the Han River basin. During the Joseon Dynasty, it belonged to the Inchang-bang and Dumo-bang districts within the 'Seongjeo Sipri' (Ten-Li Perimeter) of Hanseongbu. It was the eastern outskirts of the capital, home to Dumo-po—where goods from the upper Han River were gathered—Salgoteui-beol, the king’s hunting grounds, and Dokseodang, a school for training officials. Seongdong-gu was established in 1943 as part of a municipal reorganization. It took on its current form in 1975 when the area south of the Han River was separated to form Gangnam-gu, and again in 1995 when the area east of Dongil-ro was separated to form Gwangjin-gu. Since the Japanese colonial period, it has developed into a key transportation hub and semi-industrial area centered around Wangsimni Station.",
    people: "It is said that the name Wangsimni originates from a legend in which Great Monk Muhak, while searching for a site to establish the capital, was told by an old man to ‘go ten ri further’ (往十里). Salgote Bridge, which connects the Sagun-dong and Seongsu-dong areas, is a stone bridge built in the early Joseon Dynasty. It is designated as a National Treasure and is associated with a legend in which King Taejo, Yi Seong-gye, shot an arrow at King Taejong, but it struck a pillar; he interpreted this as a sign of divine will. Additionally, Anjeongsa Temple in Hawangsimni-dong is said to have been founded during the Silla Dynasty and later rebuilt by Venerable Muhak.",
    images: [
      { src: "Image/Seongdong-1.jpg", caption: "Wangsimni (Legend of Great Monk Muhak) · Salgote Bridge · Anjeongsa Temple and Kim Sang-ok’s Uprising (AI-generated image)" }
    ]
  }, 

  "성북구": {
    desc: "This autonomous district is situated on the rolling hills north of Seoul’s city walls, where the foothills of Mount Bukhansan extend into Mount Gaewun. It is an area where the historic cultural and arts village of Seongbuk-dong blends with the university district, and where traces of modern and contemporary culture—such as the Gansong Art Museum and Simu-jang—remain deeply embedded.",
    history: "During the Three Kingdoms period, it was a border region where the three kingdoms vied for control of the Han River basin. In the Joseon Dynasty, it belonged to the Sungshin-bang and Inchang-bang districts within the 'Seongjeo Sipri' (Ten Li Around the Capital) of Hanseongbu, serving as the northern gateway to the capital. Samseonpyeong in Seongbuk-dong was home to a military training ground and the Bukchang gate of the Royal Guard Command, and it also served as a key thoroughfare for merchants traveling along the northeastern arterial road that passed through Hyehwa Gate and led to Wonsan. In 1949, Seongbuk-gu was established by merging part of Dongdaemun-gu with the former Sungin-myeon area of Goyang County; subsequently, in 1973, Dobong-gu was separated from it, and after several boundary adjustments, the district has evolved into its current form. In modern times, as various universities and writers and painters began to gather here, the area established itself as a leading center of education and culture in Seoul.",
    people: "The Gansong Art Museum in Seongbuk-dong houses Korean cultural treasures that Jeon Hyung-pil preserved by spending his own fortune during the Japanese colonial period; it is known to hold several National Treasures, including the Hunminjeongeum Haerye (Explanation of the Proper Sounds for the Instruction of the People). It is said that Simu-jang, where Manhae Han Yong-un spent his final years, was deliberately built facing north to turn his back on the Japanese Government-General of Korea, and it remains a place that exemplifies his unwavering integrity. Additionally, local legends are passed down, such as the story of Angamnae Bridge, which was built in front of the village after a vegetable vendor named An Gam pleaded for a bridge to be constructed.",
    images: [
      { src: "Image/Seongbuk-1.jpg", caption: "Gansong Art Museum (Hunminjeongeum Haerye) · Simu-jang (Han Yong-un) · Jeongneung (Queen Sindeok) (AI-generated image)" }
    ]
  },  

  "송파구": {
    desc: "Located in southeastern Seoul on the south bank of the Han River, this autonomous district is a historic area that served as the center of Hanseong Baekje, where the Baekje Kingdom first established its capital. Today, it has grown into a commercial and cultural hub of southeastern Seoul, represented by the Olympic facilities in the Jamsil area, Lotte World, and Seokchon Lake.",
    history: "People have lived here since ancient times, as evidenced by Paleolithic and Bronze Age artifacts unearthed in the Garak-dong and Munjeong-dong areas. Around the turn of the Common Era, Baekje established its capital in this region, laying the foundation for 500 years of Hanseong Baekje centered on the Pungnap and Mongchon earthen fortresses. During the Joseon Dynasty, the area belonged to Jungdae-myeon in Gwangju-bu, and the Songpa Market, centered around Songpa Ferry, flourished as a major marketplace attracting merchants from across the country. In 1963, the area was incorporated into Seoul; after passing through Seongdong-gu, Gangnam-gu, and Gangdong-gu, it was separated from Gangdong-gu in 1988, and Songpa-gu was established. In the 1970s, the comprehensive development of the Jamsil District connected Jamsil Island—which had been an island in the river—to the mainland, and the construction of large-scale apartment complexes gave the area its current appearance.",
    people: "The Pungnap Earthen Fortress and Mongchon Earthen Fortress in Pungnap-dong and Bangi-dong, along with the burial mounds in Seokchon-dong and Bangi-dong, are precious heritage sites that reveal traces of the royal family and the capital’s residents during the Hanseong Baekje period, bearing witness to Seoul’s 2,000-year history. In Seokchon-dong, the Samjeondo Stele—erected under pressure from the Qing Dynasty following the Manchu Invasion of 1636—remains, recounting the painful history of King Injo’s surrender to the Qing Emperor Taizong. Furthermore, the Songpa Sandae Nori and Songpa Bridge-Stepping rituals, which were once performed at the thriving Songpa Market centered around Songpa Ferry, have been passed down to this day, carrying on the lively culture of the old marketplace.",
    images: [
      { src: "Image/Songpa-1.jpg", caption: "Pungnap, Mongchon Earthen Fortress, Seokchon Burial Mounds, Samjeondo Stele, Songpa Sandae Nori (AI-generated image)" }
    ]
  }, 

  "양천구": {
    desc: "This autonomous district is located in the lowlands of the Gimpo Plain in southwestern Seoul, where the Anyangcheon Stream meets the Han River. It has grown into a media hub with a high concentration of broadcasting companies, as well as the large-scale apartment complexes and private tutoring districts of the Mok-dong New Town, and has reclaimed its former name, ‘Yangcheon.’",
    history: "During the Three Kingdoms period, it served as a strategic military stronghold along the lower Han River, as evidenced by remaining ruins such as the earthen fortress in Sinjeong-dong. It became Gongam-hyeon during the Unified Silla period and was named ‘Yangcheon (陽川)’ during the reign of King Chungseon of Goryeo. During the Joseon Dynasty, it functioned as Yangcheon County, governed by a fifth-rank county magistrate, and remained an independent administrative unit for a long time; however, its name disappeared when it was incorporated into Gimpo County following the Japanese colonial government’s administrative reorganization in 1914. After being incorporated into Seoul in 1963, it was part of Yeongdeungpo-gu and Gangseo-gu; when the population surged due to the development of the Mok-dong New Town, it was separated from Gangseo-gu in 1988, and Yangcheon-gu was established. Thus, after 74 years, the area regained the old name 'Yangcheon' that it had lost in 1914.",
    people: "Yangcheon Hyanggyo, located next to the former Yangcheon County government office, is the only hyanggyo in Seoul. Although it is now part of Gangseo-gu, it is a heritage site that shares the roots of the name ‘Yangcheon.’ In Sinjeong-dong, Samhaeju—a precious liquor brewed in three stages—is preserved as an Intangible Cultural Heritage of Seoul, and in Mok-dong, the craftsmanship of Chogojang, a traditional weaving workshop specializing in patterned stone mats, continues to this day. Additionally, in the Gomdalle Village of Sinwol-dong, a poignant legend is passed down about a woman who lost her life while waiting for her beloved during the era of conflict between Silla and Baekje.",
    images: [
      { src: "Image/Yangcheon-1.jpg", caption: "Yangcheon Hyanggyo (Seokjeon Daeje) · Mok-dong Hwamunseok Weaving Workshop · Sinwol-dong Gomdalle Legend (AI-generated image)" }
    ]
  },

  "영등포구": {
    desc: "This autonomous district is located in southwestern Seoul, on a low, flat alluvial plain where the Han River and Anyang Stream converge. As the first area south of the Han River to be developed into an urban center, it serves as a hub for industry and commerce. Yeouido, an island in the middle of the river, is home to a high concentration of the National Assembly, broadcasting stations, and financial institutions, making it a key center for politics and the economy.",
    history: "In ancient times, it was part of the Mahan confederacy and early Baekje. After a period of rivalry among the Three Kingdoms, it belonged to Gogyang County during the Unified Silla period and to Geumju (衿州) during the Goryeo period. During the Joseon Dynasty, it was a rural area along the Han River corresponding to the Sangbuk and Habuk townships of Geumcheon and Siheung counties. During the Japanese colonial period, it grew into a major industrial area as factories—including spinning and flour mills—sprang up in large numbers, taking advantage of its location as the junction of the Gyeongin and Gyeongbu lines. In 1943, it became Yeongdeungpo-gu following the implementation of the district system. After liberation, it covered a vast area south of the Han River, but its boundaries were gradually reduced to their current size as Gwanak, Gangseo, and Guro districts were successively separated. Since the 1970s, with the development of Yeouido and the construction of bridges, it has established itself as a new center of Seoul and a hub for media and finance.",
    people: "In Yeongdeungpo-dong 4-ga, the former Gyeongseong Textile Office Building—a symbol of the textile industry built with Korean capital during the Japanese colonial period—remains as a Nationally Registered Heritage Site, showcasing the history of modern industry and architecture. At Bamgoji Pass in Singil-dong, a tradition of holding the Bugundang ritual is passed down alongside a legend that when a funeral procession passed by, horses’ hooves would stick to the ground; there is also the folktale of Yun Jeong-seung at Banghakgot, where a carp is said to have saved his life. Furthermore, various Bugundang shrines—such as those in Dangsan-dong and Yeongdeungpo-dong—have been preserved, maintaining the folk belief traditions of riverside villages.",
    images: [
      { src: "Image/Yeongdeungpo-1.jpg", caption: "Yeouido, the former Gyeongseong Textile Office Building, and the Han River Bugun-dang (Dangsan Fishermen’s Festival) (AI-generated image)" }
    ]
  },

  "용산구": {
    desc: "This autonomous district is situated along the route connecting downtown Seoul and Gangnam, stretching from the southern slopes of Namsan Mountain to the Han River. It has long served as a strategic hub for military bases and railways, and is an international district home to Itaewon and the embassies of 41 countries, as well as a place where history and culture blend harmoniously, featuring attractions such as the National Museum of Korea, the War Memorial of Korea, and Hyochang Park.",
    history: "In ancient times, it was part of the Mahan Confederacy and early Baekje. After the rivalry among the Three Kingdoms, it became part of Hanyang County during the Unified Silla period and belonged to Yangju during the Goryeo Dynasty. It was such a strategic hub for Han River water transport that it was even considered as a candidate site when the Southern Capital was established. During the Joseon Dynasty, it belonged to the Yongsan-bang, Hangang-bang, and Dunji-bang districts within the ten-ri perimeter of Hanseongbu. Logistics on the Han River flowed through the area centered on the Yongsan River, and transportation routes such as Itaewon and Cheongpa Station were developed. After the opening of the ports, a foreign settlement formed in the Wonhyo-ro area, and following the victory in the Russo-Japanese War, the Japanese Empire established military and railway bases on Sinyeongsan, turning the area into a stronghold for colonial rule and continental aggression. After liberation, the headquarters of the South Korean and U.S. militaries were established there, and recently, with the relocation of the U.S. military base, the creation of Yongsan Park and the development of the International Business District are underway.",
    people: "Hyochang Park in Hyochang-dong was originally the burial ground of Crown Prince Munhyo, the eldest son of King Jeongjo, but it has now established itself as a sacred site of national spirit where the remains of the three patriots—Yun Bong-gil, Lee Bong-chang, and Baek Jeong-gi—as well as key figures of the Provisional Government, including Baekbeom Kim Gu, are interred. Saenamteo and Dang-gogae in Ichon-dong are holy sites where numerous Catholics, including Father Kim Dae-geon, were martyred, and the Itaewon area is home to stories about place names steeped in the pain of the Imjin War. Additionally, at the General Nam-i Shrine in Yongmun-dong, the legend of Nam-i’s marriage—in which he is said to have revived the daughter of Kwon Ram when he was a child—is preserved, and the General Nam-i Shrine Festival continues as a Seoul Intangible Cultural Heritage.",
    images: [
      { src: "Image/Yongsan-1.jpg", caption: "Hyochang Park (Three Martyrs·Kim Gu), Saenamteo, Danggogae, General Nam-i Shrine (AI-generated image)" }
    ]
  }, 

  "은평구": {
    desc: "This autonomous district is located in a basin at the northwestern tip of Seoul, surrounded by the foothills of Mount Samgak (Bukhansan) and Mount Baekryeon. As a key stop along the old official road connecting Seoul to Uiju, it is home to many historic temples such as Jingwansa and Samcheonsa, and serves as a leading residential area in the northwest, featuring Eunpyeong New Town and the Yeonsinnae commercial district.",
    history: "In ancient times, it was part of the Mahan Confederacy and early Baekje. After the power struggles among the Three Kingdoms, it became part of Hanyang County during the Unified Silla period and belonged to Yangju during the Goryeo Dynasty. It was a strategic location at the foot of Mount Samgak, home to Yeongseo Station and temples such as Jingwansa and Samcheonsa. During the Joseon Dynasty, it belonged to the Yeon-eun-bang and Sangpyeong-bang districts in the northern part of Hanseong-bu; the name ‘Eunpyeong’ itself derives from the combination of these two place names. As the gateway to Uiju, through which Chinese envoys traveled, it was a strategically important crossroads in terms of politics, diplomacy, and military affairs. In 1914, it became Eunpyeong-myeon in Goyang County, but in 1949, it was incorporated into Seoul and became part of Seodaemun-gu. In 1979, it was separated from Seodaemun-gu to form the newly established Eunpyeong-gu. Since the 1960s, land readjustment in the Bulgwang and Yeokchon districts has transformed farmland into residential lots, and the area has recently been transformed into a new residential district through the Eunpyeong New Town development.",
    people: "On Bibong Peak of Mount Samgaksan in Jingwan-oe-dong, there is the site of King Jinheung’s royal inspection stele on Mount Bukhansan, which attests to the expansion of the Silla realm; the original stele is preserved at the National Museum of Korea. In the Imalsan area of Jingwannae-dong, there is a burial ground for eunuchs of the Joseon royal court, which serves as a valuable historical record of their lives. Additionally, various folk tales have been passed down, such as the story of 'Grandma Bap,' who is said to have disguised Nojeokbong Peak as a rice sack and poured lime into the Changneung Stream to repel Japanese invaders during the Imjin War, and the legend of Won Du-pyo of Dokbakgol, which is linked to the plot for the Injo Restoration.",
    images: [
      { src: "Image/Eunpyeong-1.jpg", caption: "Bibong: King Jinheung’s Inscription Stele, Jingwansa Temple, the Royal Eunuch’s Tomb on Imalsan Mountain, and the Gupabal SanDae Nori (AI-generated image)" }
    ]
  },

  "종로구": {
    desc: "Located in a feng shui-blessed basin with Baekak Mountain as its central peak and Naksan and Inwangsan Mountains flanking it on either side, this is the heart of the capital that served as the seat of the Joseon Dynasty for 600 years. It is an autonomous district that encapsulates Seoul’s politics, history, and culture, home to the palaces of Gyeongbokgung, Changdeokgung, Changgyeonggung, and Gyeonghuigung; the Jongmyo Shrine and Sajikdan Altar; the Blue House and government agencies; and the Jongno commercial district extending from Unjongga.",
    history: "In ancient times, it served as the stage for the Jin and Mahan confederacies and early Baekje. After the rivalry among the Three Kingdoms, it became Hanyang County during the Unified Silla period and was part of Yangju and Namgyeong during the Goryeo period—a strategic location so important that it was considered a candidate for the royal capital. In 1394, when King Taejo Yi Seong-gye moved the capital to Hanyang, the palace, the Jongmyo Shrine, the Sajik Altar, the city walls, government offices, market streets, and roads were established in this area according to the principles of ‘palaces on the left, government offices on the right’ and ‘ancestral shrines in front, markets behind,’ making it the center of the royal capital. Unjongga, lined with the Six Market Halls, formed the core of the city center. In 1943, with the implementation of the district system, Jongno-gu was established, taking its name from the bell tower (Jongnu) in Unjongga. In 1975, it incorporated parts of Seodaemun-gu and Dongdaemun-gu to reach its current boundaries. Major events in modern and contemporary history, including the March 1st Movement and the April 19 Revolution, took place here, establishing the area as a symbolic stage for politics and the democracy movement.",
    people: "Jongno-gu is home to a concentration of sites symbolic of the Joseon Dynasty—including the Jongmyo Shrine and Changdeokgung Palace, both designated as UNESCO World Heritage Sites, as well as national treasure-level palace architecture such as Geunjeongjeon Hall and Gyeonghoeru Pavilion at Gyeongbokgung Palace, along with the Sajikdan Altar, Munmyo Confucian Shrine, and Sungkyunkwan University—accounting for about half of Seoul’s designated cultural heritage sites. On Bibong Peak of Mount Samgak, there is the site of King Jinheung’s inspection tour, which illustrates Silla’s territorial expansion, while the Ten-Story Stone Pagoda at Wongaksa Temple Site and Tapgol Park together bear witness to the history of Joseon Buddhism and the March 1st Movement. In addition, numerous folktales related to the capital—such as the legend of Seonbawi Rock, which recounts the dispute between Jeong Do-jeon and Muhak over the location of the capital, and the legend of Chimabawi Rock on Inwangsan Mountain—as well as folk songs like the 'Gyeongbokgung Taryeong' and the 'Hangangsu Taryeong' have been passed down through the generations.",
    images: [
      { src: "Image/Jongno-1.jpg", caption: "Jongmyo, Gyeongbokgung Palace, Changdeokgung Palace, Tapgol Park, Wongaksa Temple, March 1st Declaration (AI-generated image)" }
    ]
  },

  "중구": {
    desc: "Located south of Cheonggyecheon Stream and on the northern slopes of Namsan Mountain, this autonomous district spans half of the Seoul Basin and is the smallest in area among the city’s 25 districts. It is Seoul’s premier central business district, with a high concentration of financial, commercial, media, and printing industries in the Myeong-dong, Eulji-ro, Sogong-dong, and Chungmu-ro areas, and is a place where commerce and history coexist, featuring landmarks such as Namdaemun Market, Namsan, and Deoksugung Palace.",
    history: "In ancient times, this area was part of the Mahan Confederacy and early Baekje. After a period of rivalry among the Three Kingdoms, it became part of Hanyang County during the Unified Silla period and belonged to Namgyeong during the Goryeo Dynasty, with this area serving as the heart of Namgyeong. During the Joseon Dynasty, it comprised the entire southern region and part of the western region of Hanseongbu, forming Namchon (South Village) within the capital walls, where the residences of the royal family and high-ranking officials, as well as shrines and royal tombs, were located. After the opening of the ports, Japanese commercial districts and economic exploitation institutions such as the Joseon Bank and the Oriental Development Company were established in the Namdaemun, Myeong-dong, and Chungmu-ro areas, marking the beginning of Seoul’s financial district. In 1943, with the implementation of the district system, the area within the city walls was divided into Jongno-gu and Jung-gu, marking the establishment of Jung-gu. Overcoming the damage caused by the Liberation and the Korean War, the area underwent urban redevelopment and has established itself as the central hub of Seoul’s political, economic, and cultural life today.",
    people: "Jung-gu is home to a concentration of cultural heritage sites spanning the history of the Joseon Dynasty and the modern era, including Sungnyemun (Namdaemun)—the main gate of the Joseon capital and a National Treasure—as well as Deoksugung Palace, Hwangudan, Myeongdong Cathedral, Yakhyeon Cathedral, the old Seoul Station, and the Bank of Korea headquarters. In the Namsangol Hanok Village in Pil-dong, traditional houses from the late 19th century—including the residence of Master Carpenter Lee Seung-eop—have been relocated to showcase the lifestyle of old Seoul, while in Yejang-dong on Namsan Mountain, the site of the Mokmyeok Mountain Beacon Tower, where beacon signals from Hamgyeong Province were received, still remains. In addition, various legends about place names are passed down, such as the legend of Beotigi-goe, whose name is said to have originated from the patrolmen shouting 'Beon-do' due to the high number of thieves in the area.",
    images: [
      { src: "Image/Jung-gu-1.jpg", caption: "Sungnyemun (Namdaemun), Deoksugung Palace, and Lee Seung-eop’s House in Namsangol Hanok Village (AI-generated image)" }
    ]
  },

  "중랑구": {
    desc: "Located in northeastern Seoul, this autonomous district is situated on a terrain that slopes from east to west, with the Jungnang Stream flowing along its edge and backed by a mountain range stretching from Mount Bulam to Mount Acha. It is a residential area rich in history spanning from prehistoric times to the modern era, home to the Paleolithic site in Myeonmok-dong, the Goguryeo fortresses on Mount Bonghwa and Mount Manguri, and Manguri History and Culture Park, where prominent figures from modern and contemporary history are laid to rest.",
    history: "As evidenced by the Myeonmok-dong Paleolithic site—the only one excavated in the Han River basin in Seoul—and the Bronze Age sites in Sangbong-dong and on Mount Bonghwa, this area has been inhabited since prehistoric times and is also considered a leading candidate for the location of the Hapuk Wirye Fortress. During the Three Kingdoms period, it was a border region where the three kingdoms vied for control—so much so that Goguryeo fortresses were constructed in the areas around Bonghwasan, Mangurisan, and Yongmabong. During the Joseon Dynasty, it belonged to Manguriri-myeon and Goyangju-myeon in Yangju, serving as a key junction on the royal procession route to Geonwonneung and as the site of a national ranch. In 1963, it was incorporated into Seoul and placed under the jurisdiction of the Manguri Branch Office of Dongdaemun-gu; in 1988, this area was separated to form the newly established Jungnang-gu. As urbanization progressed in this former fruit-farming region, factories and the Manguri-ro commercial district emerged, and since the 1990s, the development of new residential areas has transformed it into a leading residential district in northeastern Seoul.",
    people: "Manguri History and Culture Park, which originated from the Manguri Public Cemetery, is the final resting place of various modern and contemporary figures, including Bang Jeong-hwan, a pioneer of the children’s movement, and Oh Se-chang and Han Yong-un, who were among the 33 National Representatives. At its entrance stands the Monument to the 13-Province Righteous Army, commemorating the 1907 Jeongmi Righteous Army’s advance on Seoul, and at the summit of Bonghwasan Mountain, the site of the beacon tower has been restored, allowing the Bonghwasan Dang-gut ritual to continue as a Seoul Intangible Cultural Heritage. Additionally, the area is home to the legend of 'Jung-nang,' whose name is said to derive from a story of a filial daughter who disguised herself as a man to take the place of her blind father, who had been conscripted into forced labor, as well as the legend of the Meokgol Pear, which is said to have been cultivated by Wang Bang-yeon, who escorted King Danjong.",
    images: [
      { src: "Image/Jungnang-1.jpg", caption: "Manguri History Park (Bang Jeong-hwan, Oh Se-chang, Han Yong-un) · Bonghwasan Signal Tower · Dodaengut (AI-generated image)" }
    ]
  }
 };
